Fix for build error (backport from old commit)
Author: Taichi Kageyama <32001477+TaichiKageyama@users.noreply.github.com>
Date:   Fri Dec 27 13:56:06 2019 +0000

    Fix for build error

    On amd64: Don't use golangci-lint
    ~~~
    Running: golangci-lint
    ERRO Running error: context loading failed: no go files to analyze
    ERRO Deadline exceeded: try increase it by passing --deadline option
    FATA[0546] exit status 4
    ~~~

    On arm: Use arm32v6/golang as golang instead of arm32v7/golang
    ~~
    Step 12/24 : RUN if [ "$DQLITE" = true ]; then         curl -sfL https://github.com/rancher/dqlite-build/releases/download/v1.1.0-r5/dqlite-${ARCH}.tgz | tar xzf - -C / &&         apk add --allow-untrusted /usr/local/packages/*.apk     ;fi
     ---> Running in 4d8145cfef01
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/main/armv7/APKINDEX.tar.gz
    fetch http://dl-cdn.alpinelinux.org/alpine/v3.10/community/armv7/APKINDEX.tar.gz
    ERROR: unsatisfiable constraints:
      so:libc.musl-armhf.so.1 (missing):
        required by: sqlite-3.30.1-r0[so:libc.musl-armhf.so.1]
                     sqlite-libs-3.30.1-r0[so:libc.musl-armhf.so.1]
    ~~~

    If you specify "ARG DQLITE=false" in Dockerfile.dapper you can make contaimer image.
    but container fails to run with the following error because of runc issue.
    See: issue:494 in rancher/k3s
    ~~~
    Error syncing pod 60b4882c-cf0f-468b-82fc-7bcbb2c1230b ("metrics-server-6d684c7b5-hmkhn_kube-system(60b4882c-cf0f-468b-82fc-7bcbb2c1230b)"), skipping: failed to "CreatePodSandbox" for "metrics-server-6d684c7b5-hmkhn_kube-system(60b4882c-cf0f-468b-82fc-7bcbb2c1230b)" with CreatePodSandboxError: "CreatePodSandbox for pod \"metrics-server-6d684c7b5-hmkhn_kube-system(60b4882c-cf0f-468b-82fc-7bcbb2c1230b)\" failed: rpc error: code = Unknown desc = failed to create containerd task: OCI runtime create failed: container_linux.go:346: starting container process caused \"process_linux.go:319: getting the final child's pid from pipe caused \\\"EOF\\\"\": unknown"
    ~~~

Signed-off-by: Taichi Kageyama <32001477+TaichiKageyama@users.noreply.github.com>